version: '3.8'

services:
  # Servicio del BACKEND
  temperaturas-backend:
    build: 
      context: ./backend #Construye imagen desde esa carpeta
    container_name: temperaturas-backend
    restart: always #Si el contenedor se cae, se reinicia solo
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development #Variable de entorno para Flask: activa modo desarrollo (logs, debug, auto-reload)
      # Flask: empaqueta una aplicación web ligera escrita en Python (Flask) dentro de un contenedor Docker

  # Servicio del FRONTEND
  temperaturas-frontend:
    build: 
      context: ./frontend #Construye imagen desde esa carpeta
    container_name: temperaturas-frontend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - TEMP_SERVER=temperaturas-backend:5000     #Aqui está la clave: le decimos dónde está el backend por su nombre de servicio
    depends_on:
      - temperaturas-backend #Arranca el backend antes del frontend
