apiVersion: v1
kind: Service #IP estable y permitir comunicaciñon entre pods
metadata:
  name: temperaturas-backend #Nombre del service dentro de kubernetes
  labels:
    app: backend-temperaturas
spec:
  clusterIP: None #No da IP fija ni load balancer -> acceso direto a los pods
  ports:
    - port: 5000
  selector: #Este service apunta a los pods con estas etiquetas
    app: backend-temperaturas
    tier: backend
---
apiVersion: apps/v1
kind: Deployment #Crea pods automaticamente, los mantiene vivos y permite actualizaciones
metadata:
  name: temperaturas-backend #Nombre del deployment dentro de kubernetes
  labels:
    app: backend-temperaturas
spec:
  selector:
    matchLabels: #Este deployment controla pods con estas etiquetas
      app: backend-temperaturas
      tier: backend
  strategy: #Estrategia de actualizacion: borra pods antiguos y luego crea los nuevos
    type: Recreate
  template: #Define como seran los pods
    metadata:
      labels: #Deben coincidir con las del slector para que el service las encuentre
        app: backend-temperaturas
        tier: backend
    spec: #Especificacionde los pods
      containers: #Lista de contenedores
        - name: temperaturas-backend
          image: afernandez28707/temperaturas-backend:latest #Imagen de DockerHub que se va a ejecutar
          ports:
            - containerPort: 5000