apiVersion: v1
kind: Service
metadata:
  name: temperaturas-frontend
  labels:
    app: frontend-temperaturas
spec:
  type: LoadBalancer # Kubernetes desde AWS crea un load balancer y da una URL publcia DNS
  ports:
    - port: 3001 #Puerto desde el que se accede desde fuera
  selector: #Conecta el service con los pods
    app: frontend-temperaturas
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperaturas-frontend
  labels:
    app: frontend-temperaturas
spec:
  selector: #Debe coincidir con template y con service
    matchLabels:
      app: frontend-temperaturas
      tier: frontend
  strategy:
    type: Recreate #Igual que backend, borra pods antes de crear nuevos
  template: #Define los pods
    metadata: #Etiquetas de conexion con el service
      labels:
        app: frontend-temperaturas
        tier: frontend
    spec:
      containers: #Lista de contenedores
        - name: temperaturas-frontend
          image: afernandez28707/temperaturas-frontend:latest #Imagen de DcoekrHub con el frontend
          ports:
            - containerPort: 3001
          env: #Esta parte es la que conecta el frontend y el backend
            - name: TEMP_SERVER
              value: "temperaturas-backend:5000"